### PR TITLE
Adding Download function to download file from telegram

### PR DESCRIPTION
**Pull request by hellonico**

### CODE REVIEW

**Comment by Otann** [comment]
Hello @hellonico ! Thank you for your contribution.
Sorry for a delay in reviewing this. Could you please add the test for this and format the code to match the rest of the file? (spaces and newlines)

**Comment by hellonico** [comment]
Hi! I somehow missed the previous message.
Was the request merged or should I re-submit again?

**Comment by Otann** [comment]
Hi, @hellonico!
I started to look at this to do a clean up myself (formatting, test and readme) but could not identify a purpose of downloading files to local filesystem as a part of the library. I think it could exist right next to your code that uses the library. ;)

But if you want a function that gets you the file's location, but not the downloading — I think that could work.

Please correct me if I misunderstood your original intention.

**Comment by hellonico** [comment]
Thank you for the follow up!

So basically, I have written a few bots that rely on images, and/or text analysis send to them. 
I agree it would be possible to write a *bot* library on top of this one, but its actually only a few lines, and really is targeted at telegram only. Hence the PR.

Let me know if that makes sense for you too. 

Nico

**Pull request closed without merging**
