### PR TITLE
Add a support `editMessageText`

### PR DESCRIPTION
**Pull request by heycalmdown**
Refer to API [editMessageText](https://core.telegram.org/bots/api#editmessagetext)

### CODE REVIEW

**Comment by Otann** [comment]
Hi! Thank you for your contribution.
Could you please add more description to a docstring and a test?

**Comment by heycalmdown** [comment]
Okay, I'll add some tomorrow, thanks.

**Comment by heycalmdown** [comment]
@Otann review please

**Comment by Otann** [comment]
@heycalmdown released `0.2.2` to clojars, thank you again for your contribution!

**Comment by heycalmdown** [comment]
Thank you!

**Pull request merged**
