### PR TITLE
Added functions for the remaining file-sending methods of the bot API

### PR DESCRIPTION
**Pull request by setzer22**
Changed send-photo into a more generic function send-file and then created the wrappers for the methods: sendDocument sendVideo and sendAudio  that were missing. Also added a macro "accepted-formats" to avoid repetition of code which allows to check wether the file to be sent has the correct format for the metod (and thus avoiding needlesly calling the API).

### CODE REVIEW

**Comment by Otann** [comment]
Wow, many thanks for this, I like it very much!

I appreciate your macro skills, but let's keep it simple with just functions?
Something like this:

```clojure
(defn is-file [value] false)
(defn of-type [value] true)
(defn assert-file-type [value extensions]
  (if (and (is-file value)
           (of-type extensions))
    (throw (ex-info "Telegram API only supports the following formats: "
                    (string/join ", " extensions)
                    " for this method (see send-document)"))))

(defn send-video [token chat-id video]
  (assert-file-type video ["mp4"])
  (send-file token chat-id video "/sendVideo" "video" "video.mp4"))
```

**Comment by Otann** [comment]
@setzer22 Also another arity with options is missing now for new functions and README file should be updated as well.
If you don't mind, I would like to merge your code and make aforementioned changes.

**Comment by setzer22** [comment]
@Otann
> Wow, many thanks for this, I like it very much!
You're welcome, I'm glad you like the changes! 

> I appreciate your macro skills, but let's keep it simple with just functions?
Yes indeed, your approach looks cleaner. Sometimes I get a bit carried away with macros.

> If you don't mind, I would like to merge your code and make aforementioned changes.
I'll have a look. Shouldn't take me much time.

Glad to be able to contribute!

**Comment by setzer22** [comment]
I implemented the aforementioned changes. Let me know if there's anything else.

**Comment by Otann** [comment]
This is looking very very good now, thank you a lot for your support!
I will release a new version to clojars later in the evening.

**Comment by Otann** [comment]
@setzer22 released `0.2.0`

**Pull request merged**
